name: 'Testing'
description: 'Testing'
inputs:
  test-boolean:
    description: 'Testing boolean input'
    required: true
    default: false
runs:
  using: "composite"
  steps: 
    - id: installing
      run: |
        echo ${{ inputs.test-boolean }}
        npm i
      shell: bash
    - id: building
      run: npm build
      shell: bash
    - id: linting
      run: npm run lint
      shell: bash
    - id: unit-testing
      run: |
        if [ ${{ inputs.test-boolean }} != false ]; then
          npm run test:local
        else
          echo "Skipping local tests"
        fi
      shell: bash
