name: 'Testing'
description: 'Testing'
inputs:
  test-boolean:
    description: 'Testing boolean input'
    required: true
    default: false
runs:
  using: "composite"
  steps: 
    - run: |
        echo {{ inputs.test-boolean }}
        npm i
      shell: bash
    - run: npm run lint
      shell: bash
 
