
name: 'Visual Diff'
description: 'Run your visual diff tests and open a PR with the new goldens as necessary'
inputs:
  TEST_PATH:
    description: 'Visual diff tests path and test names'
    default: './**/*.visual-diff.js'
  TEST_TIMEOUT:
    description: 'mocha timeout'
    default: '40000'
  VISUAL_DIFF_S3_ID:
    description: 'S3 access key id'
    required: true
  VISUAL_DIFF_S3_SECRET:
    description: 'S3 secret access key'
    required: true
  GITHUB_TOKEN:
    description: 'Token used to open the PR'
    required: true
runs:
  using: "composite"
  steps: 
    - name: Running Visual Diff Tests
      run: |
        echo "Running Visual Diff Tests"
        npm install -g mocha
        mocha ${{ inputs.TEST_PATH }} -t ${{ inputs.TEST_TIMEOUT }} || true
        TESTS_FAILED=$?
        if [ $TESTS_FAILED -ne 0 ]; then
          echo "Committing new goldens"
          exit 1;
        else
          echo "No new goldens"
          exit 0;
        fi
      env:
        VISUAL_DIFF_S3_ID: ${{ inputs.VISUAL_DIFF_S3_ID }}
        VISUAL_DIFF_S3_SECRET: ${{ inputs.VISUAL_DIFF_S3_SECRET }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
    - run: |
        echo "Done"
      shell: bash
