
name: 'Visual Diff'
description: 'Run your visual diff tests and open a PR with the new goldens as necessary'
inputs:
  TEST_PATH:
    description: 'Visual diff tests path and test names'
    default: './**/*.visual-diff.js'
  TEST_TIMEOUT:
    description: 'mocha timeout'
    default: '40000'
  VISUAL_DIFF_S3_ID:
    description: 'S3 access key id'
    required: true
  VISUAL_DIFF_S3_SECRET:
    description: 'S3 secret access key'
    required: true
  GITHUB_TOKEN:
    description: 'Token used to open the PR'
    required: true
runs:
  using: "composite"
  steps: 
    - name: Running Visual Diff Tests
      id: visual-diff-tests
      run: |
        echo "Running Visual Diff Tests"
        npm install -g mocha
        mocha ${{ inputs.TEST_PATH }} -t ${{ inputs.TEST_TIMEOUT }} --colors && TESTS_PASSED=0 || TESTS_PASSED=1
        if [ $TESTS_PASSED -ne 0 ]; then
          echo "Committing new goldens"
          git diff
        else
          echo "Visual diff tests have passed - no new goldens needed"
        fi
        echo "::set-output name=tests-passed::$(echo $TESTS_PASSED)"
      env:
        VISUAL_DIFF_S3_ID: ${{ inputs.VISUAL_DIFF_S3_ID }}
        VISUAL_DIFF_S3_SECRET: ${{ inputs.VISUAL_DIFF_S3_SECRET }}
      shell: bash
    - name: Committing New Goldens
      run: |
        if [ ${{ steps.visual-diff-tests.outputs.tests-passed }} -ne 0]; then
          echo "This worked"
        else
          echo ${{ steps.visual-diff-tests.outputs.tests-passed }}
        fi
        if [ $TESTS_PASSED -ne 0 ]; then
          echo "This also worked"
        else
          echo $TESTS_PASSED
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
