
name: 'Visual Diff'
description: 'Run your visual diff tests and open a PR with the new goldens as necessary'
inputs:
  TEST_PATH:
    description: 'Visual diff tests path and test names'
    default: './**/*.visual-diff.js'
  TEST_TIMEOUT:
    description: 'mocha timeout'
    default: '40000'
  VISUAL_DIFF_S3_ID:
    description: 'S3 access key id'
    required: true
  VISUAL_DIFF_S3_SECRET:
    description: 'S3 secret access key'
    required: true
  GITHUB_TOKEN:
    description: 'Token used to open the PR'
    required: true
runs:
  using: "composite"
  steps: 
    - name: Running Visual Diff Tests
      id: visual-diff-tests
      run: |
        echo "Running Visual Diff Tests"
        npm install mocha -g
        mocha ${{ inputs.TEST_PATH }} -t ${{ inputs.TEST_TIMEOUT }} --colors && echo "::set-output name=tests-passed::$(echo true)" || echo "::set-output name=tests-passed::$(echo false)"   
      env:
        VISUAL_DIFF_S3_ID: ${{ inputs.VISUAL_DIFF_S3_ID }}
        VISUAL_DIFF_S3_SECRET: ${{ inputs.VISUAL_DIFF_S3_SECRET }}
      shell: bash
    - name: Committing the New Goldens (if necessary)
      run: |
        if [ ${{ steps.visual-diff-tests.outputs.tests-passed }} == true ]; then
          echo -e "\e[32mVisual diff tests have passed - no new goldens needed."
          exit 0;
        fi
        echo -e "\e[31mVisual diff tests failed - generating new goldens."
        npm install @octokit/rest --prefix ${{ github.action_path }} --no-save --loglevel error
        node ${{ github.action_path }}/src/commit-goldens.js
        git diff
        exit 1;
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        PULL_REQUEST_BRANCH: ${{ github.event.pull_request.head.ref }}
        PULL_REQUEST_NUM: ${{ github.event.number }}
      shell: bash
    - name: Committing New Goldens
      run: |
        git diff
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
