
name: 'Visual Diff'
description: 'Run your visual diff tests and open a PR with the new goldens as necessary'
inputs:
  TEST_PATH:
    description: 'Visual diff tests path and test names'
    default: './**/*.visual-diff.js'
  TEST_TIMEOUT:
    description: 'mocha timeout'
    default: '40000'
  VISUAL_DIFF_S3_ID:
    description: 'S3 access key id'
    required: true
  VISUAL_DIFF_S3_SECRET:
    description: 'S3 secret access key'
    required: true
  GITHUB_TOKEN:
    description: 'Token used to open the PR'
    required: true
runs:
  using: "composite"
  steps: 
    - name: Running Visual Diff Tests
      id: visual-diff-tests
      run: |
        echo -e "\e[34mRunning Visual Diff Tests"
        npm install mocha -g
        mocha ${{ inputs.TEST_PATH }} -t ${{ inputs.TEST_TIMEOUT }} --colors && echo "::set-output name=tests-passed::$(echo true)" || echo "::set-output name=tests-passed::$(echo false)"
        if [ -f failed-reports.txt ]; then
          FAILED_REPORTS=$(<failed-reports.txt)
          echo "::set-output name=failed-reports::$(echo "$FAILED_REPORTS")"
          rm failed-reports.txt
        fi
      env:
        FORCE_COLOR: 3
        VISUAL_DIFF_S3_ID: ${{ inputs.VISUAL_DIFF_S3_ID }}
        VISUAL_DIFF_S3_SECRET: ${{ inputs.VISUAL_DIFF_S3_SECRET }}
      shell: bash
    - name: Committing the New Goldens (if necessary)
      run: |
        if [ ${{ steps.visual-diff-tests.outputs.tests-passed }} == true ]; then
          echo -e "\e[32mVisual diff tests have passed - no new goldens needed."
          exit 0;
        fi
        echo -e "\e[31mVisual diff tests failed - generating new goldens."
 
        echo -e "\n\e[34mCreating the Visual Diff Branch"
        git checkout -b $VISUAL_DIFF_BRANCH
        
        echo -e "\n\e[34mCommitting new goldens"
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m 'Updating Visual Diff Goldens'
        
        echo -e "\n\e[34mPushing the Visual Diff Branch"
        git push --force origin $VISUAL_DIFF_BRANCH
        
      env:
        FORCE_COLOR: 3
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        VISUAL_DIFF_BRANCH: ghworkflow/visual-diff-${{ github.event.number }}
      shell: bash
    - name: Handling the Goldens PR (if necessary)
      run: |   
        if [ ${{ steps.visual-diff-tests.outputs.tests-passed }} == true ]; then
          echo -e "\n\e[34mClosing Goldens PR and Deleting Branch (if it exists)"
          git push -d origin $VISUAL_DIFF_BRANCH || true
          exit 0;
        fi

        echo -e "\n\e[34mHandling Goldens PR"
        npm install chalk --prefix ${{ github.action_path }} --no-save --loglevel error
        npm install @octokit/core --prefix ${{ github.action_path }} --no-save --loglevel error
        node ${{ github.action_path }}/handle-pr.js
 
        exit 1;
      env:
        FAILED_REPORTS: ${{ steps.visual-diff-tests.outputs.failed-reports }}
        FORCE_COLOR: 3
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        PULL_REQUEST_BRANCH: ${{ github.event.pull_request.head.ref }}
        PULL_REQUEST_NUM: ${{ github.event.number }}
        VISUAL_DIFF_BRANCH: ghworkflow/visual-diff-${{ github.event.number }}
      shell: bash
